### ISSUE TITLE
Please use an open source hardware license for non-code components

### ISSUE THREAD

**Issue by penyuan** [remipch/solar_concentrator#1]
This is an amazing project, thank you so much @remipch for sharing it!! Fantastic work. ❤️

Other than the code (which is GPLv3), I see that the other components currently use the CC BY-NC-SA 4.0 license, which is *not* an open source license according to the [Open Source Definition](https://opensource.org/osd/) *and* the [Open Source Hardware Definition](https://www.oshwa.org/definition/). 

Please either: 

(a) Change the current project README line 50 `* Open source :unlock:` to `* Open source code with source available hardware components :unlock:`

**OR**

(b) Change the `electronics` and `mechanics` folders to use an open source hardware license. There is an open source hardware license called the [CERN Open Hardware License v2 Strongly Reciprocal](https://choosealicense.com/licenses/cern-ohl-s-2.0/) that is the hardware equivalent of the GPLv3. 

I would humbly suggest option (b), and could submit a pull request if that helps. 

Thanks again for this project!

**Comment by remipch** [comment]
Thanks @penyuan for your interest.

I must admit that I'm not an expert on open source licenses, I chose one that seems to meet my needs for distributing my work.

Can you elaborate on why CC BY-NC-SA 4.0 is not an open source license?

I will study your license suggestion next week.

**Comment by penyuan** [comment]
> Thank you @penyuan for your suggestion, it makes sense.
> 
> I have changed hardware license to "CERN Open Hardware License v2 Strongly Reciprocal".

Fantanstic. ❤️ Thank you so much!!!
